services:
  postgres:
    image: postgres:16-alpine
    container_name: journaledge_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: journaledge_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d journaledge_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
